#!/usr/bin/perl

use strict;
use warnings;
use Debconf::Client::ConfModule ':all';

$| = 1;

sub ask($)
{
	my @ret = go();
	$ret[0] == 0 or die "Failed to ask debconf for $_[0]: $ret[1]\n";
}

sub get_passwd()
{
	while (1) {
		input('medium', 'ejabberd/password');
		input('medium', 'ejabberd/verify');
		ask('password');

		my $pass1 = get('ejabberd/password');
		my $pass2 = get('ejabberd/verify');
		if ($pass1 eq $pass2) {
			last;
		} else {
			input('medium', 'ejabberd/nomatch');
			ask('different passwords banner');
		}
	}
}

sub get_credentials()
{
	my $user = get('ejabberd/user');
	if ($user eq '') {
		$user = 'admin';
	}
	subst('ejabberd/user', 'user', $user);

	my $host = get('ejabberd/hostname');
	if ($host eq '') {
		$host = 'hostname';
	}
	subst('ejabberd/user', 'hostname', $host);

	input('medium', 'ejabberd/user');
	ask('user');

	$user = get('ejabberd/user');
	if ($user ne '') {
		get_passwd();
	}
}

input('medium', 'ejabberd/hostname');
ask('hostname');

if (! -e '/var/lib/ejabberd/.admin_registered') {
	get_credentials();
}

exit(0);

