.TH ejabberdctl 8 "27 September 2006" "Version 1.1.2" "ejabberdctl manual page"

.SH NAME
ejabberd Jabber/XMPP server control interface

.SH SYNOPSIS
.PP 
\fBejabberdctl\fR \fI[--node node] [vhost server] command [options]\fP

.SH DESCRIPTION
.PP 
\fBejabberdctl\fR  is a front end to the ejabberd Jabber/XMPP server.
It is designed to help the administrator control the functioning of the
running \fBejabberd\fR daemon.

.SH OPTIONS
.TP
.BI \-\-node " node"
Specifies remote erlang node to connect to. Default value is
\fIejabberd\fP. (\fBejabberdctl\fP also honors ERLANG_NODE
environment variable, which can be set in /etc/default/ejabberd, see below).
If the node name does not contain symbol \fI@\fP
then actual node name becomes \fInode@host\fP where \fIhost\fP is short
hostname (usually it coincides with \fI`hostname -s`\fP). If the node name
contain symbol \fI@\fR and its hostname part is a FQDN then \fBejabberd\fR
will use so-called long names (see \fBerl\fR(1) manual page and look for
options \fI-name\fP and \fI-sname\fP for details).

Examples of \fI--node\fP option:

.BI ejabberd
Connect to locally run ejabberd server at node \fIejabberd@`hostname -s`\fP.

.BI ejabberd@otherhost
Connect to remotely run ejabberd server at node \fIejabberd@otherhost\fP.

.BI ejabberd@localhost
Connect to locally run ejabberd server at node \fIejabberd@localhost\fP.

.TP
.BI vhost " server"
Specifies that \fIcommand\fP should be executed for virtual host \fIserver\fP.
There are only few commands that require \fIvhost\fP argument.

.PP
If there are no \fIvhost server\fP options then the \fIcommand\fP can be any
of the following:
.TP
.BI status
Requests status of the ejabberd server.
.TP
.BI stop
Stops the ejabberd server.
.TP
.BI restart
Restarts the ejabberd server.
.TP
.BI reopen-log
Force the ejabberd server to reopen its log file.
.TP
.BI register " user server password"
Register user \fIuser\fP with password \fIpassword\fP at ejabberd virtual
host \fIserver\fP.
.TP
.BI unregister " user server"
Unregister user \fIuser\fP at ejabberd virtual host \fIserver\fP.
.TP
.BI backup " filepath"
Backup user database of the ejabberd server to file \fIfilepath\fP.
.TP
.BI restore " filepath"
Restore user database of the ejabberd server from backup file \fIfilepath\fP.
.TP
.BI install-fallback " filepath"
Install a backup to \fIfilepath\fP as fallback. The fallback will be
used to restore the database at the next start-up.
.TP
.BI dump " filepath"
Dump user database of the ejabberd server to text file \fIfilepath\fP.
.TP
.BI load " filepath"
Restore user database of the ejabberd server from text file \fIfilepath\fP.
.TP
.BI import-file " filepath"
Import user data from jabberd 1.4 spool file \fIfilepath\fP. For example, if
\fIfilepath\fP is \fI.../example.org/user.xml\fP then imported username will be
\fIuser\fP and it will be imported to virtual server \fIexample.org\fP.
.TP
.BI import-dir " directorypath"
Import user data from jabberd 1.4 spool directory \fIdirectorypath\fP. Directory
name should be the name of virtual server to import users.
.TP
.BI delete-expired-messages
Delete expired offline messages from ejabberd database.
.TP
.BI user-resources " user server"
List all connected resources of user \fIuser@server\fP.
.TP
.BI connected-users-number
Report number of established users' sessions.
.TP
.BI connected-users
List all established users' sessions.

.PP
If there are \fIvhost server\fP options then the \fIcommand\fP can be
the following:
.TP
.BI registered-users
List all registered at the ejabberd server users (at virtual host \fIserver\fP).

.SH OPTIONS FILE
.PP 
The file \fB/etc/default/ejabberd\fR contains specific options. One of them
is used by \fBejabberdctl\fP.

.PD 0
.I ERLANG_NODE
Use specified string as erlang node of \fBejabberd\fP server to connect. It
overrides default \fBejabberd\fP node name. The string may take one of the
following forms: \fBnodename\fP, \fBnodename@hostname\fP or
\fBnodename@hostname.domainname\fP

.SH FILES
.PD 0
.I /etc/default/ejabberd
default variables

.SH SEE ALSO 
.PP 
\fBerl\fR(1), \fBejabberd\fR(8), \fBmnesia\fR(3).

.PP 
The program documentation is available at
\fIhttp://www.process-one.net/en/projects/ejabberd/\fP. 
A copy of the documentation can be found at
/usr/share/doc/ejabberd/guide.html.
 
.SH AUTHORS
.PP 
This manual page was adapted by Sergei Golovan <sgolovan@nes.ru> for 
the \fBDebian\fP system (but may be used by others) from the
\fBejabberd\fP documentation written by Alexey Shchepin <alexey@sevcom.net>.

Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 


