#! /bin/sh
# prerm script for ejabberd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/doc/packaging-manual/

case "$1" in
    remove|upgrade)
	if ejabberdctl status >/dev/null ; then
	    BACKUP=$(mktemp -p /var/tmp/ ejabberd-database.XXXXXX)
	    chown ejabberd:ejabberd $BACKUP
	    ejabberdctl backup $BACKUP
	    chmod 600 $BACKUP
	    echo
	    echo The ejabberd database has been backed up to $BACKUP.
	    echo
	fi
    ;;

    deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

#DEBHELPER#

exit 0

