#!/bin/sh

ERLANG_NODE=ejabberd
[ -f /etc/default/ejabberd ] && . /etc/default/ejabberd

if [ -r /var/lib/ejabberd/.erlang.cookie ] ; then
    HOME=/var/lib/ejabberd
    export HOME
fi

ERL=/usr/bin/erl

if [ $# -ne 0 ] ; then
    case $1 in
	--node) shift ; ERLANG_NODE=$1 ; shift ;;
    esac
fi

if [ "$ERLANG_NODE" = "${ERLANG_NODE%.*}" ] ; then
    SNAME=-sname
else
    SNAME=-name
fi

exec $ERL $SNAME ejabberdctl \
    -pa /usr/lib/ejabberd/ebin \
    -s ejabberd_ctl \
    -noinput \
    -extra $ERLANG_NODE "$@"

