#!/bin/sh

if [ -r /var/lib/ejabberd/.erlang.cookie ]
then
    HOME=/var/lib/ejabberd
    export HOME
fi

NODE=ejabberd@`hostname -s`

if [ $# -ne 0 ]
then
    case $1 in
	--node)
	    shift
	    if [[ $1 == *@* ]]
	    then
		NODE=$1
	    else
		NODE=$1@`hostname -s`
	    fi
	    shift ;;
    esac
fi

exec erl -noinput -sname ejabberdctl -s ejabberd_ctl -extra $NODE "$@"

